name: Run Build

on:
  pull_request:
    branches:
      - main
env:
  VITE_AUTH: ${{ secrets.VITE_AUTH }}
  VITE_URL: ${{ secrets.VITE_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install gotty dependencies
        run: |
          cd gotty/js
          npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
